### ISSUE TITLE
Null Pointer Exception onTouchEvent

### ISSUE THREAD

**Issue by CanGokdere** [apradanas/simple-linkable-text#3]
My problem is as follows, I am using linkableedittext in a fragment. When I first see the activity everything is fine, edittext request focus and I start typing. When I close the keyboard and the re-touch on edit text to get focus, it gives me crash report.  
java.lang.NullPointerException
            at android.widget.Editor.onTouchUpEvent(Editor.java:1927)
            at android.widget.TextView.onTouchEvent(TextView.java:8865)
            at android.view.View.dispatchTouchEvent(View.java:7817)

I saw something like this: http://stackoverflow.com/questions/22563891/crash-on-samsung-devices-for-edittext-containing-links

So, I also think problem is with LinkMovementMethod. Any suggestions for me to fix it or does library requires an update for the solution ?

Edit: Testing on Samsung Galaxy S3

**Comment by siyanew** [comment]
Yes, I have This Problem too

**Comment by snowdream** [comment]
Yes, I have This Problem too

**Comment by Erica1217** [comment]
Yes, I have This Problem too
